groups:
- name: host_resource_alerts
  rules:
  - alert: HostCpuUsageInfo
    expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 30
    for: 2m
    labels:
      severity: info Severidade baixa/informativa
    annotations:
      summary: "Uso de CPU moderado no host (instance {{ $labels.instance }})"
      description: "Uso de CPU > 30% nos últimos 2 minutos.\n  VALOR ATUAL = {{ $value | printf \"%.2f\" }}%\n  LABELS = {{ $labels }}"

  - alert: HostCpuUsageWarning 
    expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 50
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Uso de CPU elevado no host (instance {{ $labels.instance }})"
      description: "Uso de CPU > 50% nos últimos 2 minutos.\n  VALOR ATUAL = {{ $value | printf \"%.2f\" }}%\n  LABELS = {{ $labels }}"

  - alert: HostCpuUsageCritical
    expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 75
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Uso de CPU alto no host (instance {{ $labels.instance }})"
      description: "Uso de CPU > 75% nos últimos 2 minutos.\n  VALOR ATUAL = {{ $value | printf \"%.2f\" }}%\n  LABELS = {{ $labels }}"

  - alert: HostMemoryUsageWarning 
    expr: 100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100) > 50
    for: 2m
    labels:
      severity: warning 
    annotations:
      summary: "Uso de memória elevado no host (instance {{ $labels.instance }})"
      description: "Uso de memória > 50% nos últimos 2 minutos.\n  VALOR ATUAL = {{ $value | printf \"%.2f\" }}%\n  LABELS = {{ $labels }}"

  - alert: HostMemoryUsageCritical 
    expr: 100 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100) > 75
    for: 2m
    labels:
      severity: critical 
    annotations:
      summary: "Uso de memória alto no host (instance {{ $labels.instance }})"
      description: "Uso de memória > 75% nos últimos 2 minutos.\n  VALOR ATUAL = {{ $value | printf \"%.2f\" }}%\n  LABELS = {{ $labels }}"

  - alert: HostHighDiskSpaceUsage
    expr: (node_filesystem_avail_bytes{mountpoint="/",fstype!="tmpfs"} / node_filesystem_size_bytes{mountpoint="/",fstype!="tmpfs"}) * 100 < 10
    for: 5m
    labels:
      severity: critical 
    annotations:
      summary: "Uso de disco alto no host (instance {{ $labels.instance }}, mountpoint {{ $labels.mountpoint }})"
      description: "Espaço em disco disponível < 10% em {{ $labels.mountpoint }} nos últimos 5 minutos.\n  VALOR DISPONÍVEL = {{ $value | printf \"%.2f\" }}%\n  LABELS = {{ $labels }}"
